server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: larrypage
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 138368193606-pt6gv64nhr5tejtb2hj406uoe7l65pnt.apps.googleusercontent.com
            client-secret: wxlCM2Ldmtsfrlj9H2v6XsHK
            scope:
            - email
            - profile
          facebook:
            client-id: 825037714803248
            client-secret: 33f959766171fe4091546e85ec3e2079
            scope:
            - email
            - public_profile    
            
            
            
              